# Use this to define project wide services. This should be used sparingly as services should be defined for each individual mu-plugin where possible.
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Monolog\Handler\NewRelicHandler:
        public: true

    # BoxUk\Plugins\Base\Wonolog\Handler\QueryMonitorHandler:
    #     public: true

